require 'vapir-common/external/core_extensions'
module Vapir
  KeyCodes = (('0'..'9').to_a+('a'..'z').to_a).inject({}){|hash, char| hash.merge(char.to_sym => char.vapir_ord) }.merge(
  {
    :cancel        => 3,
    :help          => 6,
    :back_space    => 8,
    :tab           => 9,
    :clear         => 12,
    :return        => 13,
    :enter         => 14,
    :shift         => 16,
    :control       => 17,
    :alt           => 18,
    :pause         => 19,
    :caps_lock     => 20,
    :escape        => 27,
    :space         => 32,
    :page_up       => 33,
    :page_down     => 34,
    :end           => 35,
    :home          => 36,
    :left          => 37,
    :up            => 38,
    :right         => 39,
    :down          => 40,
    :printscreen   => 44,
    :insert        => 45,
    :delete        => 46,
    :semicolon     => 59,
    :equals        => 61,
    :context_menu  => 93,
    :numpad0       => 96,
    :numpad1       => 97,
    :numpad2       => 98,
    :numpad3       => 99,
    :numpad4       => 100,
    :numpad5       => 101,
    :numpad6       => 102,
    :numpad7       => 103,
    :numpad8       => 104,
    :numpad9       => 105,
    :multiply      => 106,
    :add           => 107,
    :separator     => 108,
    :subtract      => 109,
    :decimal       => 110,
    :divide        => 111,
    :f1            => 112,
    :f2            => 113,
    :f3            => 114,
    :f4            => 115,
    :f5            => 116,
    :f6            => 117,
    :f7            => 118,
    :f8            => 119,
    :f9            => 120,
    :f10           => 121,
    :f11           => 122,
    :f12           => 123,
    :f13           => 124,
    :f14           => 125,
    :f15           => 126,
    :f16           => 127,
    :f17           => 128,
    :f18           => 129,
    :f19           => 130,
    :f20           => 131,
    :f21           => 132,
    :f22           => 133,
    :f23           => 134,
    :f24           => 135,
    :num_lock      => 144,
    :scroll_lock   => 145,
    :comma         => 188,
    :dash          => 189,
    :period        => 190,
    :slash         => 191,
    :back_quote    => 192,
    :open_bracket  => 219,
    :back_slash    => 220,
    :close_bracket => 221,
    :quote         => 222,
    :meta          => 224,
  })
  PrintKeyCodes = (('0'..'9').to_a+('a'..'z').to_a).inject({}){|hash, char| hash.merge(char => char.to_sym) }.merge(
  {
    "\t" => :tab,
    #"\n" => :return,
    #"\n" => :enter,
    ' '  => :space,
    ';'  => :semicolon,
    '='  => :equals,
    ','  => :comma,
    '.'  => :period,
    '/'  => :slash,
    "`"  => :back_quote,
    '['  => :open_bracket,
    "\\" => :back_slash,
    ']'  => :close_bracket,
    "'"  => :quote,
  }).inject({}){|hash, (key, key_codes_key)| hash.merge(key => KeyCodes[key_codes_key]) }
  ShiftPrintKeyCodes = ('A'..'Z').to_a.inject({}){|hash, char| hash.merge(char => char.downcase.to_sym) }.merge(
  {
    ')' => :'0',
    '!' => :'1',
    '@' => :'2',
    '#' => :'3',
    '$' => :'4',
    '%' => :'5',
    '^' => :'6',
    '&' => :'7',
    '*' => :'8',
    '(' => :'9',
    ':' => :semicolon,
    '+' => :equals,
    '<' => :comma,
    '>' => :period,
    '?' => :slash,
    '~' => :back_quote,
    '{' => :open_bracket,
    '|' => :back_slash,
    '}' => :close_bracket,
    '"' => :quote,
  }).inject({}){|hash, (key, key_codes_key)| hash.merge(key => KeyCodes[key_codes_key]) }
  NumpadKeyCodes = ('0'..'9').inject({}){|hash, char| hash.merge(char => "numpad#{char}".to_sym) }.merge(
  {
    '*' => :multiply,
    '+' => :add,
    #? => :separator,
    '-' => :subtract,
    '.' => :decimal,
    '/' => :divide,
  }).inject({}){|hash, (key, key_codes_key)| hash.merge(key => KeyCodes[key_codes_key]) }
end
