require 'rubygems'
gem 'hoe', '1.4.0'
require 'hoe'
require './lib/commonwatir.rb'

Hoe.new('commonwatir', CommonWatir::VERSION) do |p|
  p.rubyforge_name = 'wtr'
  p.extra_deps << 'user-choices'
end
